apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-service-db
spec:
  serviceName: order-service-db
  replicas: 1
  selector:
    matchLabels:
      app: order-service-db
  template:
    metadata:
      labels:
        app: order-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: scram-sha-256
            - name: POSTGRES_INITDB_ARGS
              value: "--auth-host=scram-sha-256"
          envFrom:
            - secretRef:
                name: order-service-db-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-db
spec:
  selector:
    app: order-service-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
